data: data/WithTimeWindows3/100.10.1.json
pop_size: 80
gen: 200
max_depth: 6
c_rate: 0.8
m_rate: 0.2
tourn_size: 4
seed: 42
assignment_n: 4
time_slot: 0
file_name: 100.10.1
solution_type: without_time_slot
